#pragma once
#include <string>
#include <vector>
#include <iostream>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <iterator>
#include <cstring>
#include <cstdlib>
#include <cstdio>
#include <cstdint>
#include <cstdarg>